### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films with minimum duration
GET {{baseUrl}}/films?minimum-duration=90


### Read a single film
GET {{baseUrl}}/films/1

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json


{
    "title": "New Film Title",
    "director": "New Directore",
    "duration": 120,
    "budget": 100,
    "description": "A new film description",
    "imageUrl": "https://example.com/new-film-image.jpg"
}